recipe: default.v1
language: it

pipeline:
  - name: SpacyNLP
    model: "it_core_news_lg"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: "SpacyEntityExtractor"
    dimensions: ["PER", "LOC"]
  - name: "DucklingEntityExtractor"
    url: "http://duckling:8000"
    dimensions: ["time", "number"]
    locale: "it_IT"
    timezone: "Europe/Rome"
    timeout: 3
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.7

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
    core_fallback_threshold: 0.4
    core_fallback_action_name: "action_default_fallback"
    enable_fallback_prediction: True
  - name: UnexpecTEDIntentPolicy
    max_history: 20
    epochs: 100
  - name: TEDPolicy
    max_history: 20
    epochs: 100
    constrain_similarities: true
